CREATE TABLE CLIENTE (
	IDCLIENTE SERIAL PRIMARY KEY,
	NOME VARCHAR(150),
	CPF CHAR(11) UNIQUE,
	EMAIL VARCHAR(150) UNIQUE,
	DATA_NASCIMENTO DATE
);

CREATE TABLE PRODUTO (
	IDPRODUTO SERIAL PRIMARY KEY,
	NOME VARCHAR(150),
	CODIGO VARCHAR(50),
	MARCA VARCHAR(100),
	TIPO VARCHAR(100)
);

CREATE TABLE VENDA (
	IDVENDA SERIAL PRIMARY KEY,
	DATA_VENDA DATE,
	VALOR FLOAT,
	FORMA_DE_PAGAMENTO VARCHAR(150),
	IDCLIENTE INTEGER,
	FOREIGN KEY(IDCLIENTE) REFERENCES CLIENTE(IDCLIENTE)
);

CREATE TABLE ITEMPRODUTO (
	IDITEMPRODUTO SERIAL PRIMARY KEY,
	IDVENDA INTEGER,
	IDPRODUTO INTEGER,
	QUANTIDADE INTEGER,
	FOREIGN KEY(IDVENDA) REFERENCES VENDA(IDVENDA),
	FOREIGN KEY(IDPRODUTO) REFERENCES PRODUTO(IDPRODUTO)
);

